### ISSUE TITLE
Create a template

### ISSUE THREAD

**Issue by bullbesh** [bullbesh/whatime#2]
Structural view at graphic editor Inkscape for more comfortable work in the future.

**Comment by bullbesh** [comment]
When I start to create template, I found that current template suits me completely. All I have done is other color palettes.

Here are some of them:

![template_whatime](https://user-images.githubusercontent.com/69913622/168323458-690f2cb2-e428-458d-9b67-c1937907ff5e.png)

**Comment by bullbesh** [comment]
Current version:

![image](https://user-images.githubusercontent.com/69913622/168323640-08a63ab5-071c-4a5a-b8be-9394d0789e54.png)

**Comment by Masynchin** [comment]
Looks very familiar 🤨

**Comment by bullbesh** [comment]
> Looks very familiar 🤨

If appearance will change to the next time I will be able to see how it looks like now
